version: '3.9'

networks:
  microservico:
    name: microservico
    driver: bridge
    
services: 
  app:
    build: .
    ports:
      - 3001:3001
    volumes:
      - .:/node/app
    restart: on-failure:5
    networks:
      - microservico
    depends_on:
      - mongodb
  
  mongodb:
    image: prismagraphql/mongo-single-replica:5.0.3
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: MongoDB2024!
      INIT_WAIT_SEC: 3
    ports:
      - 27017:27017
    networks:
      - microservico

  